//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmtpServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmtpServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      by {0} (Eric Daugherty&apos;s C# Email Server).
        /// </summary>
        internal static string EMAIL_by_0_Eric_Daugherty_s_C_Email_Server {
            get {
                return ResourceManager.GetString("EMAIL_by_0_Eric_Daugherty_s_C_Email_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received: from {0} ({0} [{1}]).
        /// </summary>
        internal static string EMAIL_Received_from_0_0_1 {
            get {
                return ResourceManager.GetString("EMAIL_Received_from_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain. Domain must be at least 5 characters (a.com, a.edu, etc...).
        /// </summary>
        internal static string Exception_Domain_must_be_at_least_5_charecters__a_com__a_edu__etc {
            get {
                return ResourceManager.GetString("Exception_Domain_must_be_at_least_5_charecters__a_com__a_edu__etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address. Specified address is empty.
        /// </summary>
        internal static string Exception_Invalid_address_Specified_address_is_empty {
            get {
                return ResourceManager.GetString("Exception_Invalid_address_Specified_address_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address. The address must be formatted as: username@domain..
        /// </summary>
        internal static string Exception_Invalid_address_The_address_must_be_formatted_as_username_domain {
            get {
                return ResourceManager.GetString("Exception_Invalid_address_The_address_must_be_formatted_as_username_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address. The username and domain address parts can not contain any of the following characters: ( ) &lt; &gt; @ , ; : \ &quot; . [ ].
        /// </summary>
        internal static string Exception_Invalid_address_The_username_and_domain_address_parts_can_not_contain_any_of_the_following_characters {
            get {
                return ResourceManager.GetString("Exception_Invalid_address_The_username_and_domain_address_parts_can_not_contain_a" +
                        "ny_of_the_following_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username. Username must be at least one charecter.
        /// </summary>
        internal static string Exception_Username_must_be_at_least_one_charecter {
            get {
                return ResourceManager.GetString("Exception_Username_must_be_at_least_one_charecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: MailFrom argument: {1} rejected.  Should be from:&lt;username@domain.com&gt;.
        /// </summary>
        internal static string Log_Connection_0_MailFrom_argument_1_rejected_Should_be_from_username_domain_com {
            get {
                return ResourceManager.GetString("Log_Connection_0_MailFrom_argument_1_rejected_Should_be_from_username_domain_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: New connection from client {1}.
        /// </summary>
        internal static string Log_Connection_0_New_connection_from_client_1 {
            get {
                return ResourceManager.GetString("Log_Connection_0_New_connection_from_client_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: RcptTo address: {1} accepted..
        /// </summary>
        internal static string Log_Connection_0_RcptTo_address_1_accepted {
            get {
                return ResourceManager.GetString("Log_Connection_0_RcptTo_address_1_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: RcptTo address: {1} rejected.  Did not pass Address Filter..
        /// </summary>
        internal static string Log_Connection_0_RcptTo_address_1_rejected_Did_not_pass_Address_Filter {
            get {
                return ResourceManager.GetString("Log_Connection_0_RcptTo_address_1_rejected_Did_not_pass_Address_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: RcptTo argument: {1} rejected.  Should be from:&lt;username@domain.com&gt;.
        /// </summary>
        internal static string Log_Connection_0_RcptTo_argument_1_rejected_Should_be_from_username_domain_com {
            get {
                return ResourceManager.GetString("Log_Connection_0_RcptTo_argument_1_rejected_Should_be_from_username_domain_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: Read: {1}.
        /// </summary>
        internal static string Log_Connection_0_Read_1 {
            get {
                return ResourceManager.GetString("Log_Connection_0_Read_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: Read Line: {1}.
        /// </summary>
        internal static string Log_Connection_0_Read_Line_1 {
            get {
                return ResourceManager.GetString("Log_Connection_0_Read_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: Reset.
        /// </summary>
        internal static string Log_Connection_0_Reset {
            get {
                return ResourceManager.GetString("Log_Connection_0_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: Wrote Line: {1}.
        /// </summary>
        internal static string Log_Connection_0_Wrote_Line_1 {
            get {
                return ResourceManager.GetString("Log_Connection_0_Wrote_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating FileSpool directory: {0}. Exception {1}.
        /// </summary>
        internal static string Log_Error_creating_FileSpool_directory_0_Exception_1 {
            get {
                return ResourceManager.GetString("Log_Error_creating_FileSpool_directory_0_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSpool directory does not exist. Attempting to create....
        /// </summary>
        internal static string Log_FileSpool_directory_does_not_exist_Attempting_to_create {
            get {
                return ResourceManager.GetString("Log_FileSpool_directory_does_not_exist_Attempting_to_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid E-Mail address detected.
        /// </summary>
        internal static string Log_Invalid_E_Mail_address_detected {
            get {
                return ResourceManager.GetString("Log_Invalid_E_Mail_address_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: MailFrom address: {1} accepted..
        /// </summary>
        internal static string Log_Mail_Connection_0_MailFrom_address_1_accepted {
            get {
                return ResourceManager.GetString("Log_Mail_Connection_0_MailFrom_address_1_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: Exception occured while processing commands: {1}.
        /// </summary>
        internal static string Log_ProcessCommands_Connection_0_Exception_occured_while_processing_commands_1 {
            get {
                return ResourceManager.GetString("Log_ProcessCommands_Connection_0_Exception_occured_while_processing_commands_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessCommands Read: {0}.
        /// </summary>
        internal static string Log_ProcessCommands_ProcessCommands_Read_0 {
            get {
                return ResourceManager.GetString("Log_ProcessCommands_ProcessCommands_Read_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0}: Error: {1}.
        /// </summary>
        internal static string Log_ProcessConnection_Connection_0_Error_1 {
            get {
                return ResourceManager.GetString("Log_ProcessConnection_Connection_0_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket closed before end of line received..
        /// </summary>
        internal static string Log_Socket_closed_before_end_of_line_received {
            get {
                return ResourceManager.GetString("Log_Socket_closed_before_end_of_line_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception occured.
        /// </summary>
        internal static string Log_Unknown_exception_occured {
            get {
                return ResourceManager.GetString("Log_Unknown_exception_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 220 {0} Welcome to Eric Daugherty&apos;s C# SMTP Server..
        /// </summary>
        internal static string Protocol_220_0_Welcome_to_Eric_Daugherty_s_C_SMTP_Server {
            get {
                return ResourceManager.GetString("Protocol_220_0_Welcome_to_Eric_Daugherty_s_C_SMTP_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 {0}.
        /// </summary>
        internal static string Protocol_MESSAGE_DEFAULT_HELO_RESPONSE_250_0 {
            get {
                return ResourceManager.GetString("Protocol_MESSAGE_DEFAULT_HELO_RESPONSE_250_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 221 Goodbye..
        /// </summary>
        internal static string Protocol_MESSAGE_GOODBYE_221_Goodbye {
            get {
                return ResourceManager.GetString("Protocol_MESSAGE_GOODBYE_221_Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 451 Address is invalid..
        /// </summary>
        internal static string Protocol_MESSAGE_INVALID_ADDRESS_451_Address_is_invalid {
            get {
                return ResourceManager.GetString("Protocol_MESSAGE_INVALID_ADDRESS_451_Address_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 501 Incorrect number of arguments..
        /// </summary>
        internal static string Protocol_MESSAGE_INVALID_ARGUMENT_COUNT__501_Incorrect_number_of_arguments {
            get {
                return ResourceManager.GetString("Protocol_MESSAGE_INVALID_ARGUMENT_COUNT__501_Incorrect_number_of_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 503 Command not allowed here..
        /// </summary>
        internal static string Protocol_MESSAGE_INVALID_COMMAND_ORDER_503_Command_not_allowed_here {
            get {
                return ResourceManager.GetString("Protocol_MESSAGE_INVALID_COMMAND_ORDER_503_Command_not_allowed_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 OK.
        /// </summary>
        internal static string Protocol_MESSAGE_OK_250_OK {
            get {
                return ResourceManager.GetString("Protocol_MESSAGE_OK_250_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 354 Start mail input; end with &lt;CRLF&gt;.&lt;CRLF&gt;.
        /// </summary>
        internal static string Protocol_MESSAGE_START_DATA__354_Start_mail_input_end_with_CRLF_CRLF {
            get {
                return ResourceManager.GetString("Protocol_MESSAGE_START_DATA__354_Start_mail_input_end_with_CRLF_CRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 554 Transaction failed..
        /// </summary>
        internal static string Protocol_MESSAGE_SYSTEM_ERROR_554_Transaction_failed {
            get {
                return ResourceManager.GetString("Protocol_MESSAGE_SYSTEM_ERROR_554_Transaction_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Command Unrecognized..
        /// </summary>
        internal static string Protocol_MESSAGE_UNKNOWN_COMMAND_500_Command_Unrecognized {
            get {
                return ResourceManager.GetString("Protocol_MESSAGE_UNKNOWN_COMMAND_500_Command_Unrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 550 User does not exist..
        /// </summary>
        internal static string Protocol_MESSAGE_UNKNOWN_USER_550_User_does_not_exist {
            get {
                return ResourceManager.GetString("Protocol_MESSAGE_UNKNOWN_USER_550_User_does_not_exist", resourceCulture);
            }
        }
    }
}
